:NewDefs

:AllowRuntimeErrors
fun foo() =
  let local(x) =
    class Foo {
      fun bar = x + foo()
    }
    (new Foo()).bar
  local(1)
foo()
//│ fun foo: () -> Int
//│ Int
//│ res
//│ Runtime error:
//│   RangeError: Maximum call stack size exceeded

fun foo(f) = 
  f(1)
foo(x => x+1)
//│ fun foo: forall 'a. (1 -> 'a) -> 'a
//│ Int
//│ res
//│     = 2

fun foo(x) = 
  let bar(f) = 
    f(x)
  bar(y => y+x)
foo(1)
//│ fun foo: Int -> Int
//│ Int
//│ res
//│     = 2

fun foo(f) = 
    f(1)
class A(y: Int){
  fun bar(z) = y+z
}
fun app(a) = 
  foo(z => a.bar(z))
app(new A(1))
//│ fun foo: forall 'a. (1 -> 'a) -> 'a
//│ class A(y: Int) {
//│   fun bar: Int -> Int
//│ }
//│ fun app: forall 'b. {bar: 1 -> 'b} -> 'b
//│ Int
//│ res
//│     = 2
